version: '3.8'

volumes:
  quiz_data:  # Volume persistant pour la base de données
  node_modules:  # Volume dédié pour node_modules

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:ro  # Mode lecture seule pour le code source
      - quiz_data:/app/data  # Volume persistant pour la base de données
    environment:
      - DATABASE_URL=sqlite:///./data/spark_quiz.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:ro  # Mode lecture seule pour le code source
      - node_modules:/app/node_modules  # Volume dédié pour node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend 