version: '3.8'

volumes:
  quiz_data:  # Volume persistant pour la base de données
  node_modules:  # Volume dédié pour node_modules
  backend_logs:  # Volume pour les logs du backend

services:
  backend:
    build: ./backend
    container_name: quiz-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:ro  # Mode lecture seule pour le code source
      - quiz_data:/app/data  # Volume persistant pour la base de données
      - backend_logs:/app/logs  # Volume persistant pour les logs
    environment:
      - DATABASE_URL=sqlite:///./data/spark_quiz.db
      - LOG_LEVEL=INFO
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - quiz-network

  frontend:
    build: ./frontend
    container_name: quiz-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:ro  # Mode lecture seule pour le code source
      - node_modules:/app/node_modules  # Volume dédié pour node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge